### PR TITLE
Suffixes for datasets

### LINKED ISSUE #51: Do structures need year/version suffixes?
ANZSCO is getting a decent update at the end of 2021, likely (surely) to be used for the 2021 Census: https://www.abs.gov.au/articles/updating-australian-and-new-zealand-standard-classification-occupations. The ABS have also indicated that updates will be 'more regular and timely'.

Updating the `anzsco` object to include new classifications/remove old ones will be necessary, but will be backwards incompatible. If this is happening every year, it'll be a problem. 

So, like the current `absmapsdata` ASGS structures (`sa12011`, `sa12016`, etc), should `anzsco` et al get a year suffix?

The benefits of this would be that old code works for more than a year. The costs are that you need to type a few more letters, and the 'last updated' year might be a bit confusing? We could keep an un-suffixed structure, eg `anzsco`, that defaults to the latest version; although that would introduce the same issues. 

I think I'm leaning towards having a year suffix for all structures, and not having an un-suffixed version. Keen to hear thoughts.

### PR DESCRIPTION
**Pull request by williamlai2**
I have added suffixes for the datasets in the package. So `anzsco2009`, `anzsic2006`, `asced_foe2001` and `asced_qual2001`. Updated documentation to go with it. 

Hopefully this is what you are after.

Closes #51

### CODE REVIEW

**Comment by wfmackey** [comment]
Thanks @williamlai2! This is great. I'll have a look through tonight. Would love *thoughts* from @MattCowgill and @daviddiviny (re #52 ) before merging this very good, pretty substantial backward-incompatible change.

**Comment by daviddiviny** [comment]
Should there be an underscore before the year? What does absmapsdata do?

**Comment by williamlai2** [comment]
I have used the same format as `absmapsdata`, so without an underscore, e.g. sa12011.

**Comment by wfmackey** [comment]
Yep it is consistent with the `absmapsdata` standard (for better or worse).

**Pull request merged**
