### PR TITLE
Aus holiday

### PR DESCRIPTION
**Pull request by peteowen1**
run all the files in data-raw to update all data files.
Aus holidays hadn't been run in ~2 years - so was missing 2023/2024 holidays which are now included.
Updated URLs for anzsco and asced.
Old URL was broken for create_aus_skills.R - found new URL but data structure has changed in the spreadsheet so have commented out that data-raw file for now until we have a fix.

also added purrr (>= 1.0.0) requirement and have replaced deprecated map_df references as suggested in https://github.com/runapp-aus/strayr/issues/96

### CODE REVIEW

**Comment by MattCowgill** [comment]
Legend @peteowen1 !

**Comment by MattCowgill** [comment]
Closes https://github.com/runapp-aus/strayr/issues/96

**Comment by MattCowgill** [comment]
This looks good to me @wfmackey

**Review by wfmackey — APPROVED** [review]

**Review by MattCowgill — APPROVED** [review]
Great stuff @peteowen1 

this makes me wonder if we should have some automated GitHub action to update the holidays

**Pull request merged**
