### PR TITLE
Seifa 2021

### PR DESCRIPTION
**Pull request by peteowen1**
Included summary tables in get_seifa, with data_subclass = 'summary'.

Added the data_subclass as a column name to avoid confusion about which row is which when multiple subclasses are chosen, like current output shown below:
image

Added year as a column name - again to avoid confusion.

Treat hyphens as missing in the spreadsheets so that score columns get read in as numeric class instead of character.

### CODE REVIEW

**Comment by wfmackey** [comment]
@peteowen1 given SA codes are stored as characters in `absmapsdata` (eg: `class(sa42021$sa4_code_2021)` is character, would it be better to set `area_code` variables to be characters, too?

**Comment by wfmackey** [comment]
e.g. desired behaviour of:

```r
get_seifa(structure = c("lga"),
          data_subclass = c("ieo"),
          year = NULL) %>% 
  dplyr::select(1:4) %>% 
  dplyr::glimpse()

Rows: 548                                                                     
Columns: 4
$ data_subclass <chr> "ieo", "ieo", "ieo", "ieo", "ieo", "ieo", "ieo", "ieo", …
$ structure     <chr> "lga", "lga", "lga", "lga", "lga", "lga", "lga", "lga", …
$ area_code     <chr> "10050", "10180", "10250", "10300", "10470", "10500", "1…
$ area_name     <chr> "Albury", "Armidale Regional", "Ballina", "Balranald", "…
```

it's just one line to change and i'll add a commit

**Comment by peteowen1** [comment]
@wfmackey forgot about this - have updated one line of code to make area_code a character variable

**Comment by JustGitting** [comment]
Hi all,

Will this be merged in the future? Looks like it should be good to go, no?

**Review by wfmackey — APPROVED** [review]

**Pull request merged**
